circle: start using virtualenv
look like the google/cloud-sdk Docker image changed somehow and no longer allows installing system-wide packages with pip, even as root. I get:

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz...

https://app.circleci.com/pipelines/github/snarfed/granary/2911/workflows/71b17189-dd97-462e-be0f-f676d3884c24/jobs/5002

see: https://discuss.circleci.com/t/how-do-i-pin-a-docker-image-pip-install-virtualenv-started-failing-on-google-cloud-sdk-latest/52178