temporarily disable reddit
API changed behavior (maybe?) and it's breaking us. punting since we may port to loginpass or python-social-auth instead.

https://console.cloud.google.com/errors/CKfclf3fsLq9Ww
```
TypeError: UserSubreddit(display_name='u_Jeros18') is not JSON serializable
  at json_dumps (/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/webutil/util.py:1459)
  at get (/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/reddit.py:126)
```

https://console.cloud.google.com/errors/CODR3IHIl_GYYA
```
prawcore.exceptions.OAuthException: invalid_grant error processing request
  at _request_token (/layers/google.python.pip/pip/lib/python3.9/site-packages/prawcore/auth.py:158)
  at authorize (/layers/google.python.pip/pip/lib/python3.9/site-packages/prawcore/auth.py:242)
  at authorize (/layers/google.python.pip/pip/lib/python3.9/site-packages/praw/models/auth.py:53)
  at get (/layers/google.python.pip/pip/lib/python3.9/site-packages/oauth_dropins/reddit.py:119)
```