hopefully fix flaky test failure
eg https://circleci.com/gh/snarfed/granary/978. exception below. i had PyYAML installed globally on my laptop, and my granary virtualenv included system packages, which is why i couldn't repro it locally.

fix is to import oauth_dropins.webutil.test, which calls dev_appserver.fix_sys_path(), so that it finds app engine's bundled yaml. flakiness was due to nondeterministic test ordering; this is evidently the only test that didn't import oauth_dropins.webutil.test.

```
ERROR: test_api (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_api
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/project/test_api.py", line 10, in <module>
    from oauth_dropins.webutil import testutil_appengine
  File "/tmp/oauth-dropins/oauth_dropins/webutil/testutil_appengine.py", line 4, in <module>
    from google.appengine.datastore import datastore_stub_util
  File ".../google/appengine/datastore/datastore_stub_util.py", line 60, in <module>
    from google.appengine.api import datastore_admin
  ...
  File ".../google/appengine/datastore/datastore_index.py", line 61, in <module>
    import yaml
ImportError: No module named yaml
```