fix test_api imports
was causing flakiness on circle like this in https://circleci.com/gh/snarfed/granary/929 :

```
ERROR: test_api (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_api
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/root/project/test_api.py", line 9, in <module>
    from oauth_dropins.webutil import testutil_appengine
  File "/tmp/oauth-dropins/oauth_dropins/webutil/testutil_appengine.py", line 4, in <module>
    from google.appengine.datastore import datastore_stub_util
  File ".../google/appengine/datastore/datastore_stub_util.py", line 56, in <module>
    from google.appengine.api import datastore_admin
  File ".../google/appengine/api/datastore_admin.py", line 46, in <module>
    from google.appengine.api import datastore
  File ".../google/appengine/api/datastore.py", line 63, in <module>
    from google.appengine.datastore import datastore_query
  File ".../google/appengine/datastore/datastore_query.py", line 65, in <module>
    from google.appengine.datastore import datastore_index
  File ".../google/appengine/datastore/datastore_index.py", line 61, in <module>
    import yaml
ImportError: No module named yaml
```